import { ArrowRight, BookOpen, Boxes, Braces, CheckCircle2, FileJson2, GitBranch, PlayCircle, ShieldAlert, TestTube2 } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader, SectionTitle } from '../components/UI'

const docs: Array<{ icon: LucideIcon; title: string; text: string; to: string; label: string }> = [
  { icon: BookOpen, title: 'Project README', text: 'Value proposition, feature map, setup, deployment, and the complete demo walkthrough.', to: '#readme', label: 'Read overview' },
  { icon: Boxes, title: 'Architecture', text: 'Components, data flow, trust boundaries, state model, and operational profiles.', to: '/architecture', label: 'Open architecture' },
  { icon: ShieldAlert, title: 'Threat model', text: 'Assets, threat actors, abuse cases, mitigations, residual risk, and scope boundaries.', to: '#threat-model', label: 'Review threats' },
  { icon: FileJson2, title: 'API reference', text: 'REST resources, representative payloads, errors, and local OpenAPI access.', to: '#api', label: 'Browse endpoints' },
  { icon: PlayCircle, title: 'Demo walkthrough', text: 'A concise recruiter-facing path through the completed PAY-1842 scenario.', to: '/workflow', label: 'Start walkthrough' },
  { icon: TestTube2, title: 'Testing strategy', text: 'Policy unit tests, API contract checks, component interactions, build, and container smoke tests.', to: '#testing', label: 'View strategy' },
]

export function DocsPage() {
  return <div className="page-container"><PageHeader eyebrow="Documentation hub" title="Understand, run, and evaluate ForgeGuard" description="The repository includes implementation-level documentation for the system design, security model, API, demo flow, and decisions behind the platform." />
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{docs.map(({ icon: Icon, title, text, to, label }) => { const externalPage = to.startsWith('/'); return <article key={title} className="surface group flex min-h-52 flex-col p-5 transition-colors hover:border-electric/30"><span className="flex h-10 w-10 items-center justify-center rounded-lg border border-line bg-ink/60 text-blue-300"><Icon size={18} /></span><h2 className="mt-5 text-sm font-semibold text-white">{title}</h2><p className="mt-2 flex-1 text-xs leading-5 text-slate-500">{text}</p>{externalPage ? <Link to={to} className="mt-5 inline-flex items-center gap-1.5 text-xs font-semibold text-slate-400 group-hover:text-white">{label}<ArrowRight size={13} /></Link> : <a href={to} className="mt-5 inline-flex items-center gap-1.5 text-xs font-semibold text-slate-400 group-hover:text-white">{label}<ArrowRight size={13} /></a>}</article>})}</section>
    <section id="readme" className="surface mt-6 scroll-mt-24 p-6 md:p-8"><SectionTitle eyebrow="Quick start" title="Local developer path" /><div className="grid gap-6 lg:grid-cols-[1fr_1.1fr]"><div><p className="text-sm leading-6 text-slate-400">Docker Compose starts PostgreSQL, the FastAPI service, and a static web container. The browser experience is immediately populated with the completed scenario; the API also seeds the same domain records for exploration.</p><div className="mt-5 flex flex-wrap gap-2">{['React + TypeScript','FastAPI + Pydantic','LangGraph','PostgreSQL','Local RAG','Docker Compose'].map((item) => <span key={item} className="tag">{item}</span>)}</div></div><CodeBlock lines={['cp .env.example .env','docker compose up --build','open http://localhost:8080','open http://localhost:8000/docs']} /></div></section>
    <section id="api" className="surface mt-6 scroll-mt-24 p-6 md:p-8"><SectionTitle eyebrow="REST surface" title="Versioned, typed resources" /><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="text-[9px] uppercase tracking-wider text-slate-600"><tr><th className="pb-3">Method</th><th className="pb-3">Endpoint</th><th className="pb-3">Purpose</th></tr></thead><tbody className="text-slate-400">{[['GET','/api/v1/tickets/PAY-1842','Ticket, criteria, plan, and retrieved context'],['GET','/api/v1/workflows/demo','Completed agent execution graph'],['POST','/api/v1/workflows/demo/run','Execute deterministic local graph'],['GET','/api/v1/governance/decisions','Gateway audit decisions'],['POST','/api/v1/governance/evaluate','Validate and evaluate a typed tool request'],['POST','/api/v1/approvals/APV-0042/approve','Create a simulated local draft PR artifact']].map((row) => <tr key={row[1]} className="border-t border-line/60"><td className="py-3 font-mono text-teal-300">{row[0]}</td><td className="py-3 font-mono text-blue-200">{row[1]}</td><td className="py-3">{row[2]}</td></tr>)}</tbody></table></div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section id="threat-model" className="surface scroll-mt-24 p-6"><SectionTitle icon={<ShieldAlert size={17} className="text-amber-300" />} title="Threat model at a glance" /><ul className="space-y-3">{['Prompt content cannot grant tool permissions.','Path traversal is rejected during argument validation.','High-risk actions cannot be approved by agents.','Secrets and production deployment have no registered adapter.','Audit payloads are designed to exclude sensitive values.'].map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-400"><CheckCircle2 size={14} className="mt-0.5 shrink-0 text-teal-300" />{item}</li>)}</ul></section><section id="testing" className="surface scroll-mt-24 p-6"><SectionTitle icon={<Braces size={17} className="text-violet-300" />} title="Testing strategy" /><ul className="space-y-3">{['Policy matrix allow, approval, and block cases','Tool argument schema rejection cases','Deterministic workflow completion and outputs','REST health and seeded contract checks','Workflow replay and approval UI interactions','Production build and Docker health checks'].map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-400"><CheckCircle2 size={14} className="mt-0.5 shrink-0 text-teal-300" />{item}</li>)}</ul></section></div>
    <section className="mt-6 rounded-2xl border border-electric/20 bg-gradient-to-r from-electric/[0.08] to-violet-500/[0.06] p-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="eyebrow">Recommended evaluation path</div><h2 className="mt-2 text-lg font-semibold text-white">Ticket → Workflow → Changes → Governance → Approval</h2><p className="mt-2 text-sm text-slate-500">This sequence follows the same evidence chain a reviewer receives.</p></div><Link to="/ticket" className="button button-primary shrink-0"><GitBranch size={15} /> Begin evaluation</Link></div></section>
  </div>
}

function CodeBlock({ lines }: { lines: string[] }) { return <div className="overflow-hidden rounded-xl border border-line bg-[#06101d]"><div className="flex items-center gap-2 border-b border-line px-4 py-3"><span className="h-2 w-2 rounded-full bg-red-400/60" /><span className="h-2 w-2 rounded-full bg-amber-400/60" /><span className="h-2 w-2 rounded-full bg-teal-400/60" /></div><pre className="overflow-x-auto p-4 font-mono text-[11px] leading-6 text-blue-200">{lines.map((line) => <div key={line}><span className="mr-3 text-slate-700">$</span>{line}</div>)}</pre></div> }
